language: csharp
solution: Fanray.sln
sudo: required
dist: xenial
dotnet: 2.2
mono: none
os:
  - linux

branches:  
  only:
    - v1.1.0-preview3

notifications:
  email:
    on_success: change
    on_failure: always

before_script:
  - dotnet restore

script:
  - dotnet build ./Fanray.sln
  - dotnet test --no-build .\test\Fan.UnitTests\Fan.UnitTests.csproj
  - dotnet test --no-build .\test\Fan.IntegrationTests\Fan.IntegrationTests.csproj
  - dotnet test --no-build .\test\Fan.Blog.UnitTests\Fan.Blog.UnitTests.csproj
  - dotnet test --no-build .\test\Fan.Blog.IntegrationTests\Fan.Blog.IntegrationTests.csproj
  - dotnet test --no-build .\test\Fan.Web.Tests\Fan.Web.Tests.csproj
  - dotnet test --no-build .\test\Shortcodes.Tests\Shortcodes.Tests.csproj
