language: csharp
solution: Fanray.sln
sudo: required
dist: xenial
dotnet: 2.2
mono: none
os:
  - linux

branches:  
  only:
    - master
    - dev
    - v1.1.0-preview3

notifications:
  email:
    on_success: change
    on_failure: always

before_script:
  - dotnet restore

script:
  - dotnet build ./Fanray.sln
  - ./run-tests.sh
