language: csharp
solution: Fanray.sln
sudo: required
dist: xenial
dotnet: 3.1.101
mono: none
os:
  - linux

notifications:
  email:
    on_success: change
    on_failure: always

before_script:
  - dotnet restore

script:
  - dotnet build -c Release ./Fanray.sln
  - dotnet test -c Release ./test/Fan.Tests/Fan.Tests.csproj
  - dotnet test -c Release ./test/Fan.Blog.Tests/Fan.Blog.Tests.csproj
  - dotnet test -c Release ./test/Fan.Web.Tests/Fan.Web.Tests.csproj
  - dotnet test -c Release ./test/Shortcodes.Tests/Shortcodes.Tests.csproj
