variables:
  buildConfiguration: 'Release'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'  
 
  steps:
  - script: |
      dotnet build --configuration $(buildConfiguration) 
      dotnet test --configuration $(buildConfiguration)

- job: macOS
  pool:
    vmImage: 'macOS-latest'

  steps:
  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test --configuration $(buildConfiguration)

- job: Windows
  pool:
    vmImage: 'windows-latest'
  
  steps:
  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test --configuration $(buildConfiguration)

