variables:
  buildConfiguration: 'Release'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'  
 
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.2.402'
    inputs:
      version: 2.2.402

  - script: |
      dotnet build --configuration $(buildConfiguration) 
      dotnet test

- job: macOS
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.2.402'
    inputs:
      version: 2.2.402

  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test --configuration $(buildConfiguration)

- job: Windows
  pool:
    vmImage: 'windows-latest'
  
  steps:
  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test --configuration $(buildConfiguration)

