variables:
  buildConfiguration: 'Release'

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'  
  
  steps:
#  - task: DotNetCoreInstaller@0
#    displayName: 'Use .NET Core sdk 2.2.101'
#    inputs:
#      version: 2.2.101

  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test --configuration $(buildConfiguration)

- job: macOS
  pool:
    vmImage: 'macOS-10.13'

  steps:
#  - task: DotNetCoreInstaller@0
#    displayName: 'Use .NET Core sdk 2.2.101'
#    inputs:
#      version: 2.2.101

  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test --configuration $(buildConfiguration)

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  
  steps:
#  - task: DotNetCoreInstaller@0
#    displayName: 'Use .NET Core sdk 2.2.101'
#    inputs:
#      version: 2.2.101

  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test --configuration $(buildConfiguration)

